version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: crehana_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/crehana_db
      JWT_SECRET_KEY: "cambia-esta-clave-en-produccion"
      JWT_ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:

